# Import Library and **Dataset**

In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import graphviz.backend as be
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve, confusion_matrix, classification_report
from sklearn.datasets import *
from sklearn.svm import SVC
from IPython.display import Image, display_svg, SVG
from sklearn.tree import plot_tree
from scipy.stats import linregress
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
%matplotlib inline

from sklearn.preprocessing import MinMaxScaler, LabelEncoder, OneHotEncoder

import warnings
warnings.filterwarnings('ignore')

In [18]:
df  = pd.read_csv('IRIS_Test.csv')
dt  = pd.read_csv("IRIS_Train.csv")

In [19]:
label_encoder = LabelEncoder()
dt['species'] = label_encoder.fit_transform(dt['species'])
df['species'] = label_encoder.transform(df['species'])

In [20]:
x_train = dt.drop(columns=['species'])
y_train = dt['species']
x_test = df.drop(columns=['species'])
y_test = df['species']

# Tanpa Normalisasi

## Desicion Tree




### **Gini**

In [21]:
da_gini = DecisionTreeClassifier(criterion='gini')
da_gini.fit(x_train, y_train)

DecisionTreeClassifier()

In [22]:
y_pred_g = da_gini.predict(x_test)

In [23]:
print('Accuracy of Decision Tree-Test: ', accuracy_score(y_pred_g, y_test))

Accuracy of Decision Tree-Test:  0.9333333333333333


In [24]:
conf_matrix = confusion_matrix(y_test, y_pred_g)

In [25]:
print('\n','Confusion Matrix - Test:','\n', conf_matrix)


 Confusion Matrix - Test: 
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [26]:
print(classification_report(y_test,y_pred_g))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [27]:
specificity = []
for i in range(conf_matrix.shape[0]):
    tn = np.sum(conf_matrix) - (np.sum(conf_matrix[i, :]) + np.sum(conf_matrix[:, i]) - conf_matrix[i, i])
    fp = np.sum(conf_matrix[:, i]) - conf_matrix[i, i]
    specificity.append(tn / (tn + fp))

In [28]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.90
Specificity for class 2: 1.00


### Entropy

In [29]:
da_entropy = DecisionTreeClassifier(criterion='entropy')
da_entropy.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [30]:
y_pred_e = da_entropy.predict(x_test)

In [31]:
print('Accuracy of Decision Tree-Test: ', accuracy_score(y_pred_e, y_test))

Accuracy of Decision Tree-Test:  0.9333333333333333


In [32]:
conf_matrix_e = confusion_matrix(y_test, y_pred_e)

In [33]:
print('\n','Confusion Matrix - Test:','\n', conf_matrix_e)


 Confusion Matrix - Test: 
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [34]:
print(classification_report(y_test,y_pred_e))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [35]:
specificity = []
for i in range(conf_matrix_e.shape[0]):
    tn = np.sum(conf_matrix_e) - (np.sum(conf_matrix_e[i, :]) + np.sum(conf_matrix_e[:, i]) - conf_matrix_e[i, i])
    fp = np.sum(conf_matrix_e[:, i]) - conf_matrix_e[i, i]
    specificity.append(tn / (tn + fp))

In [36]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.90
Specificity for class 2: 1.00


## KNN

### 3

In [37]:
knn_3 = KNeighborsClassifier(n_neighbors=3)

In [38]:
knn_3.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [39]:
y_pred_k3 = knn_3.predict(x_test)

In [40]:
print('Accuracy of KNN 3: ', accuracy_score(y_test,y_pred_k3))

Accuracy of KNN 3:  0.9666666666666667


In [41]:
conf_matrix_k3 = confusion_matrix(y_test, y_pred_k3)
print('\nConfusion Matrix - KNN (k=3):\n', conf_matrix_k3)


Confusion Matrix - KNN (k=3):
 [[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


In [42]:
print(classification_report(y_test,y_pred_k3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [43]:
specificity = []
for i in range(conf_matrix_k3.shape[0]):
    tn = np.sum(conf_matrix_k3) - (np.sum(conf_matrix_k3[i, :]) + np.sum(conf_matrix_k3[:, i]) - conf_matrix_k3[i, i])
    fp = np.sum(conf_matrix_k3[:, i]) - conf_matrix_k3[i, i]
    specificity.append(tn / (tn + fp))

In [44]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.95
Specificity for class 2: 1.00


### 5

In [45]:
knn_5 = KNeighborsClassifier(n_neighbors=5)

In [46]:
knn_5.fit(x_train, y_train)

KNeighborsClassifier()

In [47]:
y_pred_k5 = knn_5.predict(x_test)

In [48]:
print('Accuracy of KNN 5: ', accuracy_score(y_test,y_pred_k5))

Accuracy of KNN 5:  0.9666666666666667


In [49]:
conf_matrix_k5 = confusion_matrix(y_test, y_pred_k5)
print('\nConfusion Matrix - KNN (k=5):\n', conf_matrix_k5)


Confusion Matrix - KNN (k=5):
 [[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


In [50]:
print(classification_report(y_test,y_pred_k5))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [51]:
specificity = []
for i in range(conf_matrix_k5.shape[0]):
    tn = np.sum(conf_matrix_k5) - (np.sum(conf_matrix_k5[i, :]) + np.sum(conf_matrix_k5[:, i]) - conf_matrix_k5[i, i])
    fp = np.sum(conf_matrix_k5[:, i]) - conf_matrix_k5[i, i]
    specificity.append(tn / (tn + fp))

In [52]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.95
Specificity for class 2: 1.00


### 7

In [53]:
knn_7 = KNeighborsClassifier(n_neighbors=7)

In [54]:
knn_7.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [55]:
y_pred_k7 = knn_7.predict(x_test)

In [56]:
print('Accuracy of KNN 7: ', accuracy_score(y_test,y_pred_k7))

Accuracy of KNN 7:  1.0


In [57]:
conf_matrix_k7 = confusion_matrix(y_test, y_pred_k7)
print('\nConfusion Matrix - KNN (k=7):\n', conf_matrix_k7)


Confusion Matrix - KNN (k=7):
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [58]:
print(classification_report(y_test,y_pred_k7))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [59]:
specificity = []
for i in range(conf_matrix_k7.shape[0]):
    tn = np.sum(conf_matrix_k7) - (np.sum(conf_matrix_k7[i, :]) + np.sum(conf_matrix_k7[:, i]) - conf_matrix_k7[i, i])
    fp = np.sum(conf_matrix_k7[:, i]) - conf_matrix_k7[i, i]
    specificity.append(tn / (tn + fp))

In [60]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 1.00
Specificity for class 2: 1.00


## Naive Bayes

In [61]:
gaussian = GaussianNB()

In [62]:
gaussian.fit(x_train, y_train)

GaussianNB()

In [63]:
y_pred_nb = gaussian.predict(x_test)

In [64]:
print('Accuracy of NB: ', accuracy_score(y_test,y_pred_nb))

Accuracy of NB:  0.9333333333333333


In [65]:
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
print('\nConfusion Matrix - NB:\n', conf_matrix_nb)


Confusion Matrix - NB:
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [66]:
print(classification_report(y_test,y_pred_nb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [67]:
specificity = []
for i in range(conf_matrix_nb.shape[0]):
    tn = np.sum(conf_matrix_nb) - (np.sum(conf_matrix_nb[i, :]) + np.sum(conf_matrix_nb[:, i]) - conf_matrix_nb[i, i])
    fp = np.sum(conf_matrix_nb[:, i]) - conf_matrix_nb[i, i]
    specificity.append(tn / (tn + fp))

In [68]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.90
Specificity for class 2: 1.00


## SVM

### Kernel Linear

In [69]:
svm = SVC(kernel = 'linear')

In [70]:
svm.fit(x_train, y_train)

SVC(kernel='linear')

In [71]:
y_pred_kl = svm.predict(x_test)

In [72]:
print('Accuracy of Kernel Linear: ', accuracy_score(y_test,y_pred_kl))

Accuracy of Kernel Linear:  1.0


In [73]:
conf_matrix_kl = confusion_matrix(y_test, y_pred_kl)
print('\nConfusion Matrix - Kernel Linear:\n', conf_matrix_kl)


Confusion Matrix - Kernel Linear:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [74]:
print(classification_report(y_test,y_pred_kl))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [75]:
specificity = []
for i in range(conf_matrix_kl.shape[0]):
    tn = np.sum(conf_matrix_kl) - (np.sum(conf_matrix_kl[i, :]) + np.sum(conf_matrix_kl[:, i]) - conf_matrix_kl[i, i])
    fp = np.sum(conf_matrix_kl[:, i]) - conf_matrix_kl[i, i]
    specificity.append(tn / (tn + fp))

In [76]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 1.00
Specificity for class 2: 1.00


### Kernel Polynomial

In [77]:
svm = SVC(kernel = 'poly')

In [78]:
svm.fit(x_train, y_train)

SVC(kernel='poly')

In [79]:
y_pred_po = svm.predict(x_test)

In [80]:
print('Accuracy of Poly: ', accuracy_score(y_test,y_pred_po))

Accuracy of Poly:  0.9666666666666667


In [81]:
conf_matrix_po = confusion_matrix(y_test, y_pred_po)
print('\nConfusion Matrix - Poly:\n', conf_matrix_po)


Confusion Matrix - Poly:
 [[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


In [82]:
print(classification_report(y_test,y_pred_po))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [83]:
specificity = []
for i in range(conf_matrix_po.shape[0]):
    tn = np.sum(conf_matrix_po) - (np.sum(conf_matrix_po[i, :]) + np.sum(conf_matrix_po[:, i]) - conf_matrix_po[i, i])
    fp = np.sum(conf_matrix_po[:, i]) - conf_matrix_po[i, i]
    specificity.append(tn / (tn + fp))

In [84]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.95
Specificity for class 2: 1.00


### Kernel RBF

In [85]:
svm = SVC(kernel = 'rbf')

In [86]:
svm.fit(x_train, y_train)

SVC()

In [87]:
y_pred_rbf = svm.predict(x_test)

In [88]:
print('Accuracy of RBF: ', accuracy_score(y_test,y_pred_rbf))

Accuracy of RBF:  0.9666666666666667


In [89]:
conf_matrix_rbf = confusion_matrix(y_test, y_pred_rbf)
print('\nConfusion Matrix - RBF:\n', conf_matrix_rbf)


Confusion Matrix - RBF:
 [[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


In [90]:
print(classification_report(y_test,y_pred_rbf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [91]:
specificity = []
for i in range(conf_matrix_rbf.shape[0]):
    tn = np.sum(conf_matrix_rbf) - (np.sum(conf_matrix_rbf[i, :]) + np.sum(conf_matrix_rbf[:, i]) - conf_matrix_rbf[i, i])
    fp = np.sum(conf_matrix_rbf[:, i]) - conf_matrix_rbf[i, i]
    specificity.append(tn / (tn + fp))

In [92]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.95
Specificity for class 2: 1.00


### Kernel Sigmoid

In [93]:
svm = SVC(kernel = 'sigmoid')

In [94]:
svm.fit(x_train, y_train)

SVC(kernel='sigmoid')

In [95]:
y_pred_si = svm.predict(x_test)

In [96]:
print('Accuracy of Sigmoid: ', accuracy_score(y_test,y_pred_si))

Accuracy of Sigmoid:  0.03333333333333333


In [97]:
conf_matrix_si = confusion_matrix(y_test, y_pred_si)
print('\nConfusion Matrix - Sigmoid:\n', conf_matrix_si)


Confusion Matrix - Sigmoid:
 [[ 1  0  9]
 [ 7  0  3]
 [10  0  0]]


In [98]:
print(classification_report(y_test,y_pred_si))

              precision    recall  f1-score   support

           0       0.06      0.10      0.07        10
           1       0.00      0.00      0.00        10
           2       0.00      0.00      0.00        10

    accuracy                           0.03        30
   macro avg       0.02      0.03      0.02        30
weighted avg       0.02      0.03      0.02        30



In [99]:
specificity = []
for i in range(conf_matrix_si.shape[0]):
    tn = np.sum(conf_matrix_si) - (np.sum(conf_matrix_si[i, :]) + np.sum(conf_matrix_si[:, i]) - conf_matrix_si[i, i])
    fp = np.sum(conf_matrix_si[:, i]) - conf_matrix_si[i, i]
    specificity.append(tn / (tn + fp))

In [100]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 0.15
Specificity for class 1: 1.00
Specificity for class 2: 0.40


## ANN

In [101]:
onehot_encoder = OneHotEncoder(sparse=False)
y_train_encoded = onehot_encoder.fit_transform(y_train.values.reshape(-1, 1))
y_test_encoded = onehot_encoder.transform(y_test.values.reshape(-1, 1))

In [102]:
model = Sequential()
model.add(Dense(6, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [103]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [104]:
model.fit(x_train, y_train_encoded, batch_size=32, epochs=100, verbose=1)

Epoch 1/100
4/4 [==============================] - 2s 13ms/step - loss: 1.8546 - accuracy: 0.0000e+00
Epoch 2/100
4/4 [==============================] - 0s 7ms/step - loss: 1.7921 - accuracy: 0.0000e+00
Epoch 3/100
4/4 [==============================] - 0s 9ms/step - loss: 1.7327 - accuracy: 0.0000e+00
Epoch 4/100
4/4 [==============================] - 0s 8ms/step - loss: 1.6788 - accuracy: 0.0000e+00
Epoch 5/100
4/4 [==============================] - 0s 9ms/step - loss: 1.6219 - accuracy: 0.0000e+00
Epoch 6/100
4/4 [==============================] - 0s 9ms/step - loss: 1.5726 - accuracy: 0.0000e+00
Epoch 7/100
4/4 [==============================] - 0s 8ms/step - loss: 1.5230 - accuracy: 0.0000e+00
Epoch 8/100
4/4 [==============================] - 0s 9ms/step - loss: 1.4719 - accuracy: 0.0000e+00
Epoch 9/100
4/4 [==============================] - 0s 8ms/step - loss: 1.4232 - accuracy: 0.0000e+00
Epoch 10/100
4/4 [==============================] - 0s 8ms/step - loss: 1.3720 - accuracy:

In [105]:
loss, accuracy = model.evaluate(x_test, y_test_encoded)
print(f'\nAccuracy: {accuracy}')

1/1 [==============================] - 0s 194ms/step - loss: 0.4682 - accuracy: 0.9667

Accuracy: 0.9666666388511658


In [106]:
y_pred_prob = model.predict(x_test)
y_pred = np.argmax(y_pred_prob, axis=1)

1/1 [==============================] - 0s 98ms/step


In [107]:
conf_matrix_ann = confusion_matrix(y_test, y_pred)
print('\nConfusion Matrix - ANN:\n', conf_matrix_ann)



Confusion Matrix - ANN:
 [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [108]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [109]:
specificity = []
for i in range(conf_matrix_ann.shape[0]):
    tn = np.sum(conf_matrix_ann) - (np.sum(conf_matrix_ann[i, :]) + np.sum(conf_matrix_ann[:, i]) - conf_matrix_ann[i, i])
    fp = np.sum(conf_matrix_ann[:, i]) - conf_matrix_ann[i, i]
    specificity.append(tn / (tn + fp))

In [110]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 1.00
Specificity for class 2: 0.95


# Normalisasi

In [111]:
scaler = MinMaxScaler()
x_train_norm = scaler.fit_transform(x_train)
x_test_norm = scaler.transform(x_test)

## Desicion Tree

### Gini

In [112]:
da_gini = DecisionTreeClassifier(criterion='gini')
da_gini.fit(x_train_norm, y_train)

DecisionTreeClassifier()

In [113]:
y_pred_g = da_gini.predict(x_test_norm)

In [114]:
print('Accuracy of Decision Tree-Test: ', accuracy_score(y_pred_g, y_test))

Accuracy of Decision Tree-Test:  0.9666666666666667


In [115]:
conf_matrix = confusion_matrix(y_test, y_pred_g)

In [116]:
print('\n','Confusion Matrix - Test:','\n', conf_matrix)


 Confusion Matrix - Test: 
 [[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


In [117]:
print(classification_report(y_test,y_pred_g))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [118]:
specificity = []
for i in range(conf_matrix.shape[0]):
    tn = np.sum(conf_matrix) - (np.sum(conf_matrix[i, :]) + np.sum(conf_matrix[:, i]) - conf_matrix[i, i])
    fp = np.sum(conf_matrix[:, i]) - conf_matrix[i, i]
    specificity.append(tn / (tn + fp))

In [119]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.95
Specificity for class 2: 1.00


### Entropy

In [120]:
da_entropy = DecisionTreeClassifier(criterion='entropy')
da_entropy.fit(x_train_norm, y_train)

DecisionTreeClassifier(criterion='entropy')

In [121]:
y_pred_e = da_entropy.predict(x_test_norm)

In [122]:
print('Accuracy of Decision Tree-Test: ', accuracy_score(y_pred_e, y_test))

Accuracy of Decision Tree-Test:  0.9666666666666667


In [123]:
conf_matrix_e = confusion_matrix(y_test, y_pred_e)

In [124]:
print('\n','Confusion Matrix - Test:','\n', conf_matrix_e)


 Confusion Matrix - Test: 
 [[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


In [125]:
print(classification_report(y_test,y_pred_e))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [126]:
specificity = []
for i in range(conf_matrix_e.shape[0]):
    tn = np.sum(conf_matrix_e) - (np.sum(conf_matrix_e[i, :]) + np.sum(conf_matrix_e[:, i]) - conf_matrix_e[i, i])
    fp = np.sum(conf_matrix_e[:, i]) - conf_matrix_e[i, i]
    specificity.append(tn / (tn + fp))

In [127]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.95
Specificity for class 2: 1.00


## KNN

### 3

In [128]:
knn_3 = KNeighborsClassifier(n_neighbors=3)

In [129]:
knn_3.fit(x_train_norm, y_train)

KNeighborsClassifier(n_neighbors=3)

In [130]:
y_pred_k3 = knn_3.predict(x_test_norm)

In [131]:
print('Accuracy of KNN 3: ', accuracy_score(y_test,y_pred_k3))

Accuracy of KNN 3:  0.9333333333333333


In [132]:
conf_matrix_k3 = confusion_matrix(y_test, y_pred_k3)
print('\nConfusion Matrix - KNN (k=3):\n', conf_matrix_k3)


Confusion Matrix - KNN (k=3):
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [133]:
print(classification_report(y_test,y_pred_k3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [134]:
specificity = []
for i in range(conf_matrix_k3.shape[0]):
    tn = np.sum(conf_matrix_k3) - (np.sum(conf_matrix_k3[i, :]) + np.sum(conf_matrix_k3[:, i]) - conf_matrix_k3[i, i])
    fp = np.sum(conf_matrix_k3[:, i]) - conf_matrix_k3[i, i]
    specificity.append(tn / (tn + fp))

In [135]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.90
Specificity for class 2: 1.00


### 5

In [136]:
knn_5 = KNeighborsClassifier(n_neighbors=5)

In [137]:
knn_5.fit(x_train_norm, y_train)

KNeighborsClassifier()

In [138]:
y_pred_k5 = knn_5.predict(x_test_norm)

In [139]:
print('Accuracy of KNN 5: ', accuracy_score(y_test,y_pred_k5))

Accuracy of KNN 5:  0.9333333333333333


In [140]:
conf_matrix_k5 = confusion_matrix(y_test, y_pred_k5)
print('\nConfusion Matrix - KNN (k=5):\n', conf_matrix_k5)


Confusion Matrix - KNN (k=5):
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [141]:
print(classification_report(y_test,y_pred_k5))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [142]:
specificity = []
for i in range(conf_matrix_k5.shape[0]):
    tn = np.sum(conf_matrix_k5) - (np.sum(conf_matrix_k5[i, :]) + np.sum(conf_matrix_k5[:, i]) - conf_matrix_k5[i, i])
    fp = np.sum(conf_matrix_k5[:, i]) - conf_matrix_k5[i, i]
    specificity.append(tn / (tn + fp))

In [143]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.90
Specificity for class 2: 1.00


### 7

In [144]:
knn_7 = KNeighborsClassifier(n_neighbors=7)

In [145]:
knn_7.fit(x_train_norm, y_train)

KNeighborsClassifier(n_neighbors=7)

In [146]:
y_pred_k7 = knn_7.predict(x_test_norm)

In [147]:
print('Accuracy of KNN 7: ', accuracy_score(y_test,y_pred_k7))

Accuracy of KNN 7:  0.9333333333333333


In [148]:
conf_matrix_k7 = confusion_matrix(y_test, y_pred_k7)
print('\nConfusion Matrix - KNN (k=7):\n', conf_matrix_k7)


Confusion Matrix - KNN (k=7):
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [149]:
print(classification_report(y_test,y_pred_k7))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [150]:
specificity = []
for i in range(conf_matrix_k7.shape[0]):
    tn = np.sum(conf_matrix_k7) - (np.sum(conf_matrix_k7[i, :]) + np.sum(conf_matrix_k7[:, i]) - conf_matrix_k7[i, i])
    fp = np.sum(conf_matrix_k7[:, i]) - conf_matrix_k7[i, i]
    specificity.append(tn / (tn + fp))

In [151]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.90
Specificity for class 2: 1.00


## Naive Bayes

In [152]:
gaussian = GaussianNB()

In [153]:
gaussian.fit(x_train_norm, y_train)

GaussianNB()

In [154]:
y_pred_nb = gaussian.predict(x_test_norm)

In [155]:
print('Accuracy of NB: ', accuracy_score(y_test,y_pred_nb))

Accuracy of NB:  0.9333333333333333


In [156]:
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
print('\nConfusion Matrix - NB:\n', conf_matrix_nb)


Confusion Matrix - NB:
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [157]:
print(classification_report(y_test,y_pred_nb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [158]:
specificity = []
for i in range(conf_matrix_nb.shape[0]):
    tn = np.sum(conf_matrix_nb) - (np.sum(conf_matrix_nb[i, :]) + np.sum(conf_matrix_nb[:, i]) - conf_matrix_nb[i, i])
    fp = np.sum(conf_matrix_nb[:, i]) - conf_matrix_nb[i, i]
    specificity.append(tn / (tn + fp))

In [159]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.90
Specificity for class 2: 1.00


## SVM

### Kernel Linear

In [160]:
svm = SVC(kernel = 'linear')

In [161]:
svm.fit(x_train_norm, y_train)

SVC(kernel='linear')

In [162]:
y_pred_kl = svm.predict(x_test_norm)

In [163]:
print('Accuracy of Kernel Linear: ', accuracy_score(y_test,y_pred_kl))

Accuracy of Kernel Linear:  0.9333333333333333


In [164]:
conf_matrix_kl = confusion_matrix(y_test, y_pred_kl)
print('\nConfusion Matrix - Kernel Linear:\n', conf_matrix_kl)


Confusion Matrix - Kernel Linear:
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [165]:
print(classification_report(y_test,y_pred_kl))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [166]:
specificity = []
for i in range(conf_matrix_kl.shape[0]):
    tn = np.sum(conf_matrix_kl) - (np.sum(conf_matrix_kl[i, :]) + np.sum(conf_matrix_kl[:, i]) - conf_matrix_kl[i, i])
    fp = np.sum(conf_matrix_kl[:, i]) - conf_matrix_kl[i, i]
    specificity.append(tn / (tn + fp))

In [167]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.90
Specificity for class 2: 1.00


### Kernel Polynomial

In [168]:
svm = SVC(kernel = 'poly')

In [169]:
svm.fit(x_train_norm, y_train)

SVC(kernel='poly')

In [170]:
y_pred_po = svm.predict(x_test_norm)

In [171]:
print('Accuracy of Poly: ', accuracy_score(y_test,y_pred_po))

Accuracy of Poly:  0.9


In [172]:
conf_matrix_po = confusion_matrix(y_test, y_pred_po)
print('\nConfusion Matrix - Poly:\n', conf_matrix_po)


Confusion Matrix - Poly:
 [[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]


In [173]:
print(classification_report(y_test,y_pred_po))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.77      1.00      0.87        10
           2       1.00      0.70      0.82        10

    accuracy                           0.90        30
   macro avg       0.92      0.90      0.90        30
weighted avg       0.92      0.90      0.90        30



In [174]:
specificity = []
for i in range(conf_matrix_po.shape[0]):
    tn = np.sum(conf_matrix_po) - (np.sum(conf_matrix_po[i, :]) + np.sum(conf_matrix_po[:, i]) - conf_matrix_po[i, i])
    fp = np.sum(conf_matrix_po[:, i]) - conf_matrix_po[i, i]
    specificity.append(tn / (tn + fp))

In [175]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.85
Specificity for class 2: 1.00


### Kernel RBF

In [176]:
svm = SVC(kernel = 'rbf')

In [177]:
svm.fit(x_train_norm, y_train)

SVC()

In [178]:
y_pred_rbf = svm.predict(x_test_norm)

In [179]:
print('Accuracy of RBF: ', accuracy_score(y_test,y_pred_rbf))

Accuracy of RBF:  0.9333333333333333


In [180]:
conf_matrix_rbf = confusion_matrix(y_test, y_pred_rbf)
print('\nConfusion Matrix - RBF:\n', conf_matrix_rbf)


Confusion Matrix - RBF:
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [181]:
print(classification_report(y_test,y_pred_rbf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [182]:
specificity = []
for i in range(conf_matrix_rbf.shape[0]):
    tn = np.sum(conf_matrix_rbf) - (np.sum(conf_matrix_rbf[i, :]) + np.sum(conf_matrix_rbf[:, i]) - conf_matrix_rbf[i, i])
    fp = np.sum(conf_matrix_rbf[:, i]) - conf_matrix_rbf[i, i]
    specificity.append(tn / (tn + fp))

In [183]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 0.90
Specificity for class 2: 1.00


### Kernel Sigmoid

In [184]:
svm = SVC(kernel = 'sigmoid')

In [185]:
svm.fit(x_train_norm, y_train)

SVC(kernel='sigmoid')

In [186]:
y_pred_si = svm.predict(x_test_norm)

In [187]:
print('Accuracy of Sigmoid: ', accuracy_score(y_test,y_pred_si))

Accuracy of Sigmoid:  0.23333333333333334


In [188]:
conf_matrix_si = confusion_matrix(y_test, y_pred_si)
print('\nConfusion Matrix - Sigmoid:\n', conf_matrix_si)


Confusion Matrix - Sigmoid:
 [[5 0 5]
 [0 2 8]
 [6 4 0]]


In [189]:
print(classification_report(y_test,y_pred_si))

              precision    recall  f1-score   support

           0       0.45      0.50      0.48        10
           1       0.33      0.20      0.25        10
           2       0.00      0.00      0.00        10

    accuracy                           0.23        30
   macro avg       0.26      0.23      0.24        30
weighted avg       0.26      0.23      0.24        30



In [190]:
specificity = []
for i in range(conf_matrix_si.shape[0]):
    tn = np.sum(conf_matrix_si) - (np.sum(conf_matrix_si[i, :]) + np.sum(conf_matrix_si[:, i]) - conf_matrix_si[i, i])
    fp = np.sum(conf_matrix_si[:, i]) - conf_matrix_si[i, i]
    specificity.append(tn / (tn + fp))

In [191]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 0.70
Specificity for class 1: 0.80
Specificity for class 2: 0.35


## ANN

In [192]:
onehot_encoder = OneHotEncoder(sparse=False)
y_train_encoded = onehot_encoder.fit_transform(y_train.values.reshape(-1, 1))
y_test_encoded = onehot_encoder.transform(y_test.values.reshape(-1, 1))

In [193]:
model = Sequential()
model.add(Dense(6, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [194]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [195]:
model.fit(x_train_norm, y_train_encoded, batch_size=32, epochs=100, verbose=1)

Epoch 1/100
4/4 [==============================] - 1s 4ms/step - loss: 1.0943 - accuracy: 0.3333
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0900 - accuracy: 0.3333
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0858 - accuracy: 0.3333
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0816 - accuracy: 0.3333
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0775 - accuracy: 0.3333
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0741 - accuracy: 0.3417
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0713 - accuracy: 0.3417
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0681 - accuracy: 0.3500
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0655 - accuracy: 0.3500
Epoch 10/100
4/4 [==============================] - 0s 5ms/step - loss: 1.0627 - accuracy: 0.3500
Epoch 11/100
4/4 [===========

In [198]:
loss, accuracy = model.evaluate(x_test_norm, y_test_encoded)
print(f'\nAccuracy: {accuracy}')

1/1 [==============================] - 0s 31ms/step - loss: 0.5779 - accuracy: 0.6667

Accuracy: 0.6666666865348816


In [199]:
y_pred_prob = model.predict(x_test_norm)
y_pred = np.argmax(y_pred_prob, axis=1)

1/1 [==============================] - 0s 24ms/step


In [200]:
conf_matrix_ann = confusion_matrix(y_test, y_pred)
print('\nConfusion Matrix - ANN:\n', conf_matrix_ann)



Confusion Matrix - ANN:
 [[10  0  0]
 [ 0  0 10]
 [ 0  0 10]]


In [201]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.00      0.00      0.00        10
           2       0.50      1.00      0.67        10

    accuracy                           0.67        30
   macro avg       0.50      0.67      0.56        30
weighted avg       0.50      0.67      0.56        30



In [202]:
specificity = []
for i in range(conf_matrix_ann.shape[0]):
    tn = np.sum(conf_matrix_ann) - (np.sum(conf_matrix_ann[i, :]) + np.sum(conf_matrix_ann[:, i]) - conf_matrix_ann[i, i])
    fp = np.sum(conf_matrix_ann[:, i]) - conf_matrix_ann[i, i]
    specificity.append(tn / (tn + fp))

In [203]:
for i, spec in enumerate(specificity):
    print(f'Specificity for class {i}: {spec:.2f}')

Specificity for class 0: 1.00
Specificity for class 1: 1.00
Specificity for class 2: 0.50
